In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
print('✅ All libraries imported successfully!')

✅ All libraries imported successfully!

In [2]:
df = pd.read_csv('../data/tamil_nadu_waterborne_disease_data.csv')
print(f'✅ Dataset loaded!')
print(f'📊 Rows: {df.shape[0]}')
print(f'📋 Columns: {df.shape[1]}')
print(f'📅 Date Range: {df["date"].min()} to {df["date"].max()}')
print(f'🗺️ Districts: {df["district"].nunique()}')

✅ Dataset loaded!
📊 Rows: 1008
📋 Columns: 19
📅 Date Range: 2018-01-01 to 2024-12-01
🗺️ Districts: 12

In [3]:
df.head(10)

,date,year,month,month_name,district,rainfall_mm,temperature_celsius,pH,turbidity_NTU,coliform_count_per100ml,dissolved_oxygen_mg_L,total_dissolved_solids_mg_L,population,cholera_cases,diarrhea_cases,typhoid_cases,hepatitis_a_cases,total_disease_cases,outbreak_alert
0,2018-01-01,2018,1,January,Chennai,36.22,37.31,7.88,15.37,78.01,4.78,258.08,4544887,42,170,26,15,253,1
1,2018-02-01,2018,2,February,Chennai,13.95,34.11,8.36,1.02,496.11,7.09,811.65,1807371,62,243,44,20,369,1
2,2018-03-01,2018,3,March,Chennai,78.16,27.26,6.41,15.84,191.23,8.92,666.76,2928388,48,176,32,13,269,1
3,2018-04-01,2018,4,April,Chennai,76.42,37.52,8.06,8.31,48.84,7.42,640.15,4556518,40,154,23,14,231,1
4,2018-05-01,2018,5,May,Chennai,37.37,26.55,7.94,11.20,103.97,6.84,231.31,2595505,34,128,24,14,200,1
5,2018-06-01,2018,6,June,Chennai,167.27,28.57,7.51,17.55,624.76,8.22,947.32,3204238,100,374,54,28,556,1
6,2018-07-01,2018,7,July,Chennai,176.26,25.04,8.47,25.39,129.17,4.03,1015.46,2237095,48,194,32,14,288,1
7,2018-08-01,2018,8,August,Chennai,123.02,25.62,8.19,20.75,215.08,4.32,510.98,4642807,61,220,34,15,330,1
8,2018-09-01,2018,9,September,Chennai,147.35,29.36,8.43,27.79,469.12,5.18,456.07,622409,75,268,42,24,409,1
9,2018-10-01,2018,10,October,Chennai,290.82,33.74,6.52,27.91,485.86,5.02,1142.85,3459034,100,351,56,28,535,1

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1008 entries, 0 to 1007
Data columns (total 19 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   date                         1008 non-null   str
 1   year                         1008 non-null   int64
 2   month                        1008 non-null   int64
 3   month_name                   1008 non-null   str
 4   district                     1008 non-null   str
 5   rainfall_mm                  1008 non-null   float64
 6   temperature_celsius          1008 non-null   float64
 7   pH                           1008 non-null   float64
 8   turbidity_NTU                1008 non-null   float64
 9   coliform_count_per100ml      1008 non-null   float64
 10  dissolved_oxygen_mg_L        1008 non-null   float64
 11  total_dissolved_solids_mg_L  1008 non-null   float64
 12  population                   1008 non-null   int64
 13  cholera_cases                1008 non-null   int64
 14  diarrhea_cases               1008 non-null   int64
 15  typhoid_cases                1008 non-null   int64
 16  hepatitis_a_cases            1008 non-null   int64
 17  total_disease_cases          1008 non-null   int64
 18  outbreak_alert               1008 non-null   int64
dtypes: float64(7), int64(9), str(3)
memory usage: 175.0 KB

In [5]:
df.describe().round(2)

,year,month,rainfall_mm,temperature_celsius,pH,turbidity_NTU,coliform_count_per100ml,dissolved_oxygen_mg_L,total_dissolved_solids_mg_L,population,cholera_cases,diarrhea_cases,typhoid_cases,hepatitis_a_cases,total_disease_cases,outbreak_alert
count,1008.0,1008.00,1008.00,1008.00,1008.00,1008.00,1008.00,1008.00,1008.00,1008.00,1008.00,1008.00,1008.00,1008.00,1008.00,1008.0
mean,2021.0,6.50,133.33,30.74,7.38,16.77,317.16,6.44,718.28,2778483.22,63.99,238.10,38.82,19.28,360.19,1.0
std,2.0,3.45,100.71,4.03,0.66,9.88,205.55,1.45,288.04,1295689.61,21.07,74.18,10.55,6.25,110.35,0.0
min,2018.0,1.00,10.07,24.02,6.20,1.02,1.61,4.00,201.47,500917.00,21.00,80.00,18.00,5.00,133.00,1.0
25%,2019.0,3.75,52.44,27.24,6.80,8.82,152.43,5.18,474.35,1663613.50,49.00,185.00,31.00,15.00,282.00,1.0
50%,2021.0,6.50,106.70,30.76,7.44,15.86,297.90,6.48,721.31,2800902.50,61.00,230.00,37.00,18.00,346.00,1.0
75%,2023.0,9.25,185.02,34.11,7.92,22.86,450.66,7.69,973.90,3923862.50,75.00,279.00,45.00,23.00,421.00,1.0
max,2024.0,12.00,399.41,37.94,8.50,44.96,896.48,9.00,1199.85,4999367.00,137.00,508.00,73.00,39.00,750.00,1.0

In [6]:
missing = df.isnull().sum()
print('Missing Values:')
print(missing)
print(f'\n✅ Total missing values: {missing.sum()}')

Missing Values:
date                           0
year                           0
month                          0
month_name                     0
district                       0
rainfall_mm                    0
temperature_celsius            0
pH                             0
turbidity_NTU                  0
coliform_count_per100ml        0
dissolved_oxygen_mg_L          0
total_dissolved_solids_mg_L    0
population                     0
cholera_cases                  0
diarrhea_cases                 0
typhoid_cases                  0
hepatitis_a_cases              0
total_disease_cases            0
outbreak_alert                 0
dtype: int64

✅ Total missing values: 0

In [8]:
outbreak_count = df['outbreak_alert'].value_counts()
print('Outbreak Alert Distribution:')
print(outbreak_count)
print(f'\nOutbreak Rate: {(outbreak_count.sum())}  total records')

Outbreak Alert Distribution:
outbreak_alert
1    1008
Name: count, dtype: int64

Outbreak Rate: 1008  total records

In [9]:
print('Missing Values:')
print(df.isnull().sum())
print(f'\n✅ Total missing values: {df.isnull().sum().sum()}')

Missing Values:
date                           0
year                           0
month                          0
month_name                     0
district                       0
rainfall_mm                    0
temperature_celsius            0
pH                             0
turbidity_NTU                  0
coliform_count_per100ml        0
dissolved_oxygen_mg_L          0
total_dissolved_solids_mg_L    0
population                     0
cholera_cases                  0
diarrhea_cases                 0
typhoid_cases                  0
hepatitis_a_cases              0
total_disease_cases            0
outbreak_alert                 0
dtype: int64

✅ Total missing values: 0

In [10]:
district_summary = df.groupby('district')['total_disease_cases'].sum()
district_summary = district_summary.sort_values(ascending=False)
print('Total Cases by District:')
print(district_summary)

Total Cases by District:
district
Thanjavur          31730
Salem              31589
Coimbatore         31291
Vellore            30804
Madurai            30398
Nagapattinam       30120
Tiruppur           29908
Tiruchirappalli    29663
Cuddalore          29644
Chennai            29530
Tirunelveli        29326
Ramanathapuram     29071
Name: total_disease_cases, dtype: int64